### ISSUE TITLE
Tasks with hyphen in their name absent in workflow run results

### ISSUE THREAD

**Issue by aniewielska** [elixir-cloud-aai/cwl-WES#103]
That is another bug from a category "but you know it already".
For RD workflow (https://github.com/jarnolaitinen/RD_pipeline/blob/master/workflow.cwl)
some task names contain hyphens: gatk-ir, gatk-base_recalibration. Those tasks do not appear in the result of the run. That is because output parser only looks for words - which allows [a-zA-Z0-9_] and not a hyphen.

**Comment by uniqueg** [comment]
Can be solved together with #128 and/or #152
