### ISSUE TITLE
Refactor to support "pluggable" workflow engines

### ISSUE THREAD

**Issue by fgypas** [elixir-cloud-aai/cwl-WES#82]
**Is your feature request related to a problem? Please describe.**
Add support for making it easy to support further workflow engines than the currently supported [cwl-tes](https://github.com/common-workflow-language/cwl-tes). These may or may not be [Task Execution Schema](https://github.com/ga4gh/task-execution-schemas)-compatible.

**Describe the solution you'd like**
Before adding further workflow engines, a robust abstract solution should be conceived that answers at least the following questions:
- In what format should the individual plug-ins be? Via functions? Via classes/subclasses? In another way?
- How to deal with different types of workflow engines: (1) executables (2) Python libraries (3) WES services (4) non-WES web services (5) any other?
- How are workflow types/versions mapped to a workflow engine?
- How is installation of dependencies handled? Should all dependencies be installed? Only those configured? How will this be achieved, especially for non-pythonic engines?

For the actual addition of further services, **after** refactoring, priority should be given to engines that support TES as an endpoint, currently:
- [cwl-tes](https://github.com/common-workflow-language/cwl-tes)
- [Cromwell](https://github.com/broadinstitute/cromwell)
- [Nextflow](https://github.com/nextflow-io/nextflow)

Individual issues should be opened up for these.

**Comment by uniqueg** [comment]
This will be skipped in favor of having workflow language-specific implementations based on a [common archetype](https://github.com/elixir-cloud-aai/foca) for shared code. Mapping of workflow to WES instance will happen via [proWES](https://github.com/elixir-cloud-aai/proWES).
